name: Build Application

on: push

jobs:
  build:
      name: Build our Application
      runs-on: ubuntu-latest
      steps:
          - name: Pull code
            uses: actions/checkout@v2
          - name: Print Current Directory
            run: pwd
          - name: List Files in Directory
            run: ls
          - name: Check NPM CLI
            run: npm -v
          - name: Build the React App
            run: npm run build